# Generated by Django 5.1.6 on 2025-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionrecord",
            name="converted_format",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "DOCX"),
                    ("txt", "TXT"),
                    ("png", "PNG"),
                    ("xlsx", "XLSX"),
                    ("csv", "CSV"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="conversionrecord",
            name="file_name",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
